<?php

namespace Zyxware\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserScoreRepository extends EntityRepository
{
  public function getTopTenScores()
  {
    return $this->getEntityManager()
      ->createQuery('SELECT p.firstName, p.lastName, p.email, p.score FROM ZyxwareQuizBundle:UserScore p order by p.score DESC')
      ->setMaxResults(10)
      ->getResult();
  }
}
