<?php

namespace Zyxware\QuizBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserScoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserScoreRepository extends EntityRepository
{
}
