zyxware_quiz_homepage:
    path:     /quiz
    defaults: { _controller: ZyxwareQuizBundle:Quiz:create }
zyxware_quiz_questions:
    path:     /quiz/questions
    defaults: { _controller: ZyxwareQuizBundle:Quiz:questions }
zyxware_quiz_create:
    path:     /quiz/create
    defaults: { _controller: ZyxwareQuizBundle:Quiz:create }
zyxware_quiz_result:
    path:     /quiz/result
    defaults: { _controller: ZyxwareQuizBundle:Quiz:result }
